# Generated by Django 4.0.4 on 2022-05-10 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='data_comentario',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='comentario',
            name='titulo_noticia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp1.noticia'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='imagem',
            field=models.ImageField(upload_to='media'),
        ),
    ]
